title: Suui
email: suui.gd@gmail.com
description: My awesome site.

environment: production
permalink: /blog/:title

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - "/node_modules/"