title: Suui
email: suui.gd@gmail.com
description: My awesome site.

environment: production
url: https://suui-gd.com
permalink: /blog/:title

markdown: kramdown

gems:
  - jekyll-redirect-from

exclude:
  - "/vendor/"
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - "/node_modules/"